version: 2
jobs:
  build:
    working_directory: ~/layout-linter
    docker:
      - image: circleci/node:8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - layout-linter-npm-{{ checksum "package.json" }}
      - run: make install
      - save_cache:
          key: layout-linter-npm-{{ checksum "package.json" }}
          paths: 
            - ~/layout-linter/node_modules
      - run: make test
