defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
      environment:
        JOBS: 2
  working_directory: ~/layout-linter

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - layout-linter-node10-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: NPM Install
          command: npm install --non-interactive
      - save_cache:
          key: layout-linter-node10-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/layout-linter/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/layout-linter/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
